### PR TITLE
CI update

### PR DESCRIPTION
**Pull request by grst**
- Copy files from immunedeconv
- Reformat

TODO
 - [x] api key for coverage
 - [x] api key for netlify
 - [x] update badges

### CODE REVIEW

**Comment by grst** [comment]
@alex-d13, please look it through and LMK if anything is unclear. 

 * pkgdown currently fails with an out-of-memory issue in the sfaira vignette. Maybe there's some low-hanging fruit for reducing memory consumption? Like setting a variable to NULL in R or a `del` of an unused object in Python? 
 * The Check on windows fails also when rendering the sfaira vignette, but the error message is less clear to me. Maybe it also gets solved by reducing memory usage.

**Comment by alex-d13** [comment]
Hi,

Thanks a lot for the help, everything seems to be clear to me.

Yeah the vignettes with sfaira are an issue on itself..i usually tried to pre-compile them locally, then push the compiled pkgdown vignette to its branch manually. Thats a really annoying workflow since I have to it before every push to main, but I dont really know how to solve it differently. The vignette first has to build a conda environment using basilisk and then downloads one example dataset from sfaira. I guess thats where pkgdown has its memory issue.
Another reason for this pre-calculation is the time limit in Bioconductor. They give me timeout warnings if I build the vignette on their system.
This is the blogpost I am using to precompile the vignettes: https://ropensci.org/blog/2019/12/08/precompute-vignettes/

**Comment by grst** [comment]
I see! We can of course somehow exclude the vignette from the CI. 
The memory limit on GH actions is 7GB, which is not *too* little. 

Maybe a little downsampling or choosing a different example dataset will suffice?

**Comment by alex-d13** [comment]
I could try that, let me see if I can find a smaller dataset. 

But I don't think I can decrease the runtime, installing the python packages just takes some time. So maybe I can find a solution where pkgdown builds the vignettes and deploys them on one branch (main_deploy) and another branch to push to bioconductor (has to be the main branch i think). But i don't know if thats good 'git' solution :D

**Comment by grst** [comment]
If the vignette build runs on github, you could set it up to auto-commt the pre-compiled vignette, then bioconductor woudn't need to build it.

**Comment by grst** [comment]
You can take inspiration from the `document` action for that

**Pull request merged**
